GET http://localhost:3001/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk0NDYwNDAzLCJleHAiOjE2OTQ0NjA0NDN9.VwW9MoYf9uvv0qsxXCcUAsEbPF0L9awh2-H6mWbfQlA
###
POST http://localhost:4001/login
Content-Type: application/json

{
    "username": "Jim"
}

###

POST http://localhost:4001/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk0NDYwMzYwfQ.WGwxH9s1TeU2nVpnmMvj7cRL4qCGuMpMxk3PGuT7Wmc"
}