POST http://localhost:3000/api/register
Content-Type: application/json

{
    "email":"a@a.com",
    "password": "a"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"a@a.com",
    "password": "a"
}